In [74]:
import numpy as np
# 일반 리스트와 numpy 리스트와 비교
num1 = [1, 2, 3, 4] # 리스트
num1
num2 = [5, 6, 7, 8]
# print(num1 + num2) # 산술덧셈이 아니라 연결 - [1, 2, 3, 4, 5, 6, 7, 8]

# numpy로 리스트를 생성
x= np.array([1, 2, 3, 4]) #1행 4열
print(x)
print(type(x))
print(x.shape) #(1,4)인데 튜플형식으로 표시됨 - (4,)
print(x.dtype) # 속성 명령어 int32 - 4바이트

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
int32


In [76]:
# numpy 연산
# 1차원 리스트에서는 원소의 개수가 다르면 오류 발생. 2차원은 가능.
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x.dtype) # 8바이트

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
float64


In [52]:
# Numpy는 한 가지 자료형만 허용
a = np.array([1, 2, 'a', 'b'])
print(a) # 문자형으로 됨. 작은 자료형에서 큰 자료형으로 변환됨(형변환)

# 일반 리스트 - 여러가지 자료형 허용
cart = ['생수', '감자', 100, True] # 파이썬에서만 가능한 구조 -> Numpy에서는 안된다
cart

['1' '2' 'a' 'b']


['생수', '감자', 100, True]

In [70]:
# Numpy 이차원 리스트
# 내부 리스트의 원소의 갯수가 같아야 함 - 같지 않을 경우 오류 발생
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)

b = np.array([[1,2], [3]])
print(b)

[[1 2]
 [3 4]]
(2, 2)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [86]:
# Numpy 함수 
# zeros() - 리스트의 모든 원소를 0으로 설정
# ones() - 리스트의 모든 원소를 1으로 설정
a1 = np.zeros((3, 3)) # 3행 3열을 0으로 채움
print(a1)
print(a1.shape)

a2 = np.ones((2,3)) # 2행 3열을 0으로 채움
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [106]:
# np.arange()

import numpy as np
print(range(10))
print(list(range(10)))
print()

a = np.arange(10) + 1
print(a)

a2 = np.arange(3, 9)
print(a2)

a3 = np.arange(3, 9, 2) # step 2 추가
print(a3)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7 8]
[3 5 7]
